### ISSUE TITLE
Spring Cleaning 2018

### ISSUE THREAD

**Issue by stephenyeargin** [stephenyeargin/hubot-grafana#79]
The following checklist is for all of the Hubot packages I maintain.

#### README.md

- [x] Badges (underneath title)

```
[![npm version](https://badge.fury.io/js/hubot-PACKAGE_NAME.svg)](http://badge.fury.io/js/hubot-PACKAGE_NAME) [![Build Status](https://travis-ci.org/stephenyeargin/hubot-PACKAGE_NAME.png)](https://travis-ci.org/stephenyeargin/hubot-PACKAGE_NAME)
```

- [x] Configuration options

#### `package.json`

- [x] author

```
  "author": "Stephen Yeargin <stephen@yearg.in>",
```

- [x] repository

```
  "repository": {
    "type": "git",
    "url": "git://github.com/stephenyeargin/hubot-PACKAGE_NAME.git"
  },
```

- [x] bugs

```
  "bugs": {
    "url": "https://github.com/stephenyeargin/hubot-PACKAGE_NAME/issues"
  },
```

- [x] peerDependencies

```
  "peerDependencies": {
    "hubot": ">=2 <10 || 0.0.0-development"
  },
```

- [x] husky configuration

```
  "scripts": {
    "test": "grunt test",
    "precommit": "npm test",
    "prepush": "npm test"
  }
```

#### `Gruntfile.js`

- [x] additionalFiles

```
        additionalFiles: ['package-lock.json']
```

#### `.travis.yml`

- [x] TravisCI configuration

```
language: node_js
sudo: false
notifications:
  email: false
node_js:
  - "8" # stable
  - "6" # LTS
  - "4" # maintenance
cache:
  directories:
- node_modules
```
